name: 'Hello World Docker Action'
inputs:
  who-to-greet:
    required: true
    default: 'world'
outputs:
  time:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
